### ISSUE TITLE
Get event for multiple users.

### ISSUE THREAD

**Issue by Hirani-Pradeep** [spatie/twitter-streaming-api#11]
I want to get all event of multiple users.
Using User stream API will get the event for the single user but want to get the event for multiple users.

This code is working fine for the single user.

TwitterStreamingApi::userStream()
            ->onEventUsers(function(array $event) {
                if ($event['event'] === 'favorite') {
                    echo "Our tweet {$event['target_object']['text']} got favourited by {$event['source']['screen_name']}";
                }
            })
            ->startListening();

**Comment by freekmurze** [comment]
Listening for multiple users is not supported. You’ll find that even if you start multiple streams for single users, Twitter will shut down connections.

**Comment by Hirani-Pradeep** [comment]
Hello,
- We want to number of comments, likes, and retweets for multiple users.
- And we want to live update data for multiple users.
How to achieve above requirements.
Please help us.
