### ISSUE TITLE
Fix PHP 7.2 warnings

### ISSUE THREAD

**Issue by povesteam** [spatie/twitter-streaming-api#17]
The underlying `phirehose` package issues a warning in PHP 7.2.

There is a PR opened to fix this, but it is not merged for 4 months: https://github.com/fennb/phirehose/pull/113

What is the workflow in this case, to be able to use your package in PHP 7.2?

Thanks!

**Comment by freekmurze** [comment]
We'll just have to hope the PR in the phirohose will get merged soon.
