### ISSUE TITLE
Error in PHP 7.2

### ISSUE THREAD

**Issue by irazasyed** [spatie/twitter-streaming-api#18]
This package or rather the dependency library has an issue with PHP 7.2 and a PR is already created. However, the package maintainer doesn't seem to be active: https://github.com/fennb/phirehose/pull/113

Perhaps you can consider rewriting this with something like ReatPHP/Amphp? Or maybe use another library.

Thanks!

**Comment by freekmurze** [comment]
Let's hope @fennb will tag a new version soon.
