### ISSUE TITLE
Do not use fennb/phirehose via packagist

### ISSUE THREAD

**Issue by lorenzbausch** [spatie/twitter-streaming-api#19]
https://github.com/fennb/phirehose/issues/117 pointed out that the phirehose maintainer has no access to packagist to release new versions.
Since spatie/twitter-streaming-api is basically unusable with PHP 7.2 and it is unclear if and when a new version containing the bugfix is tagged i suggest to refer to https://github.com/fennb/phirehose.git#405d125db9baa771ac0cd861f0b2b2032434d40c directly.

What do you think?

**Comment by freekmurze** [comment]
Sounds like a good plan, send a PR.
