### ISSUE TITLE
Streams will be removed until 19.06.2018

### ISSUE THREAD

**Issue by LKaemmerling** [spatie/twitter-streaming-api#21]
Hello guys,

i wanted to use this package for a little bot, but i noticed that the userstream api will be removed until 19.06.2018 from twitter. (See https://developer.twitter.com/en/docs/accounts-and-users/subscribe-account-activity/api-reference/user-stream)

How do you handle this? Are there plans for an update?

**Comment by hurradieweltgehtunter** [comment]
thx for this info. Facing the same problem. I think using webhooks is the solution: https://developer.twitter.com/en/docs/accounts-and-users/subscribe-account-activity/api-reference/aaa-standard-all
