### ISSUE TITLE
Close Connection

### ISSUE THREAD

**Issue by cambur** [spatie/twitter-streaming-api#23]
I was wondering if there is a way to close the connection if you are not tracking anything. Might be useful for dynamic services. I can't access the clse connection method because is protected.

**Comment by freekmurze** [comment]
In normal circumstances you don't want to close the connection. When opening and starting to listen to a connection PHP will just hang.

I'm thinking the easiest way to shut down a connection is determining with another PHP script which process id is currently listening to twitter and shut that process down when needed.

If I've missed something and you know calling `close` is possible and works, feel free to submit a PR that makes the method public. But make sure it works before submitting that PR by editing your own vendor files.
