### ISSUE TITLE
install without composer

### ISSUE THREAD

**Issue by hajamirjoon** [spatie/twitter-streaming-api#25]
Hi,
would you please tell me how I can install this package without composer?

I added this code:
`require_once ('twitter-streaming-api-master/src/BaseStream.php');
require_once ('twitter-streaming-api-master/src/PublicStream.php');
require_once ('twitter-streaming-api-master/src/UserStream.php');
require_once ('twitter-streaming-api-master/src/PhirehoseWrapper.php');`

but I got this error:

> Class 'OauthPhirehose' not found

**Comment by freekmurze** [comment]
We do everything with composer. If you want to do it without you’ll need to figure this out yourself.
