### ISSUE TITLE
Hears from string and not just on hashtags

### ISSUE THREAD

**Issue by mahmod2000** [spatie/twitter-streaming-api#26]
Hi,

First of all, thanks for this great package.
I faced with an issue, it seems whenHears function just search characters in hashtags, but I would like to search in all characters besides hashtags.
Could you give me some tricks?
Does this function support what I mentioned in above?

Thank in advance.

**Comment by freekmurze** [comment]
In my project I only have to search the entire string. I don't know if it's possible to do what you mentioned above. Research it yourself, if there are changes needed to this package, feel free to PR them.
